
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
  namespace: default
data:
  traefik.toml: |
    defaultEntryPoints = ["http"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.http.auth.forward]
        address = "http://auth"
        authResponseHeaders = ["X-Forwarded-User"]
    [kubernetes]
    [respondingTimeouts]
      idleTimeout = "620s"
              