version: "3.7"
services:
  securethebox-server:
    build:
      context: .
      dockerfile: Dockerfile.securethebox-server
    restart: always
    ports:
      - 5000
  # code-server:
  #   container_name: code-server
  #   image: cavalrytactics/code-server:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "${PWD}:/home/coder/project"
  #   entrypoint:
  #     - dumb-init
  #     - code-server
  #     - --auth=none
  #     - --disable-telemetry