
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: us-central1-a-username-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
              